import { PokemonList } from './pokemon.model';



export const POKEMON_LIST: PokemonList = [
    
  {
    id: 1,
    name: 'Bulbizarre',
    life :21,
    // taille:computed((item=this.life())=>item()<=15?"petit":item()>=25?"grand":"moyen"),
    taille:0,
    damage: 5,
    picture: 'images/bulbizarre.png',
    types: ['Plante', 'Poison'],
    created: new Date(),
  },
  {
    id: 2,
    name: 'Salamèche',
    life: 28,
    taille:0,
    damage: 6,
    picture: 'images/salameche.png',
    types: ['Feu'],
    created: new Date(),
  },
  {
    id: 3,
    name: 'Carapuce',
    life: 21,
    taille:0,
    damage: 4,
    picture: 'images/carapuce.png',
    types: ['Eau'],
    created: new Date(),
  },
  {
    id: 4,
    name: 'Aspicot',
    life: 16,
    taille:0,
    damage: 2,
    picture: 'images/aspicot.png',
    types: ['Insecte', 'Poison'],
    created: new Date(),
  },
  {
    id: 5,
    name: 'Roucool',
    life: 30,
    taille:0,
    damage: 7,
    picture: 'images/roucool.png',
    types: ['Normal', 'Vol'],
    created: new Date(),
  },
  {
    id: 6,
    name: 'Rattata',
    life: 18,
    taille:0,
    damage: 6,
    picture: 'images/rattata.png',
    types: ['Normal'],
    created: new Date(),
  },
  {
    id: 7,
    name: 'Piafabec',
    life: 14,
    taille:0,
    damage: 5,
    picture: 'images/piafabec.png',
    types: ['Normal', 'Vol'],
    created: new Date(),
  },
  {
    id: 8,
    name: 'Abo',
    life: 16,
    damage: 4,
    taille:0,
    picture: 'images/abo.png',
    types: ['Poison'],
    created: new Date(1992, 11, 19),
  },
  {
    id: 9,
    name: 'Pikachu',
    life: 21,
    taille:0,
    damage: 7,
    picture: 'images/pikachu.png',
    types: ['Electrik'],
    created: new Date(1995, 1, 12),
  },
  {
    id: 10,
    name: 'Sabelette',
    life: 19,
    taille:0,
    damage: 3,
    picture: 'images/sabellete.png',
    types: ['Normal'],
    created: new Date(),
  },
  {
    id: 11,
    name: 'Mélofée',
    life: 25,
    taille:0,
    damage: 5,
    picture: 'images/melofee.png',
    types: ['Fée'],
    created: new Date(),
  },
  {
    id: 12,
    name: 'Groupix',
    life: 17,
    taille:0,
    damage: 8,
    picture: 'images/groupix.png',
    types: ['Feu'],
    created: new Date(),
  },
];